### ISSUE TITLE
Add toggle to library items to hide them from the list

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#330]
Library items won't always be displayed in the faceted search listing. Most commonly, Mary wants to create a library item and include a direct link in an email or something similar. So, the default should be to hide library items from the media library.

**Comment by marycklein** [comment]
I'm not sure I agree here. Or maybe I don't understand what you're saying.

Even though I create a library item and then announce the creation of that item by emailing the link to Friends, that does not mean that I don't want people to find the item later when they are searching for content in the library.

"I am making this a "high" priority issu only because resolving my potential objection is high priority; if there is actual work to be done on this issue, the work itself might not be high priority.)

**Comment by brylie** [comment]
We can just close the issue since it is no longer wanted or relevant
