### ISSUE TITLE
Bookstore Suppose to be Digital Store

### ISSUE THREAD

**Issue by toppylawz** [WesternFriend/WF-website#409]
The pdf book is supposed to be sent to the user's email for download after making the payment. How can one integrate that possibility?

**Comment by brylie** [comment]
Hei @toppylawz, thanks for your interest in the project.

Since Bookstore orders create an [`Order`](https://github.com/WesternFriend/WF-website/blob/2be0c4b5977f483a8f9b0bf01795158547e5a7ca/orders/models.py#L10) instance, you could use a Django `post_save` [signal](https://docs.djangoproject.com/en/4.0/topics/signals/) on the `Order` model. In the signal, you would look for a change in the `paid` field and then could send an email to the address in the `purchaser_email` field:

https://github.com/WesternFriend/WF-website/blob/2be0c4b5977f483a8f9b0bf01795158547e5a7ca/orders/models.py#L62

https://github.com/WesternFriend/WF-website/blob/2be0c4b5977f483a8f9b0bf01795158547e5a7ca/orders/models.py#L29

Granted, you would need to figure out how to store the related PDF file, since our bookstore is not handling PDFs currently. We manually send out emails for such cases.

**Comment by toppylawz** [comment]
Nice guide. Thank you.
