### ISSUE TITLE
Resize displays of embedded video

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#506]
I seem to be unable to edit size of image displayed for a Vimeo embedded in media library.
Attached pics show size of display versus the size that I “saved” in editor.
<img width="1348" alt="Screen Shot 2023-01-17 at 11 24 20 PM" src="https://user-images.githubusercontent.com/44241543/213110048-294f83b2-6358-4b05-80cd-a11b05ff66f8.png">
<img width="882" alt="Screen Shot 2023-01-17 at 11 22 55 PM" src="https://user-images.githubusercontent.com/44241543/213110062-17723719-9671-49d0-8589-612e5ff98c54.png">

**Comment by brylie** [comment]
## Video player width respects input value

Specifying the video width for uploaded media will now control the width of the displayed video.

https://sandbox.westernfriend.org/library/wf-podcast-seventeen-frank-granshaw-on-science-for-justice/
<img width="447" alt="Screenshot 2023-01-28 at 11 09 39" src="https://user-images.githubusercontent.com/17307/215257568-06676c44-06d3-47e1-8847-833bcba5c8b1.png">

The video width will apply to every place the video is displayed, such as in the media library or any other item that includes that video, due to the way Wagtailmedia stores the video width.

## Audio player width is unaffected

Since uploaded audio items don't have a `width` property, they will display at the default width for the users web browser (Chrome, Firefox, Safari, etc.).
