### ISSUE TITLE
Swap home page columns about magazine

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#509]
![Home - Swap Magazine Columns](https://user-images.githubusercontent.com/44241543/213124510-e18888b2-9db4-4bb0-9d20-a1e09346f555.jpg)

**Comment by brylie** [comment]
## Increased cover image size

Below, I've increased the maximum cover image size to the next common ratio of 800px wide.

### Before

<img width="1243" alt="Screenshot 2023-01-24 at 18 39 25" src="https://user-images.githubusercontent.com/17307/214353449-1881a5ed-4e2a-42e1-8977-1692c7c78b80.png">

### After

<img width="1243" alt="Screenshot 2023-01-24 at 18 37 19" src="https://user-images.githubusercontent.com/17307/214353163-6cf2d7eb-af74-4bcd-a0db-cb22801c7e89.png">

## Column widths

The column widths need to be considered for various screen sizes, since people will view the site on small, medium, large, and extra large screens.

The values for the two columns (left and right) should sum to 12, and are currently:

- small & medium: 8 L - 4 R
- large & x-large: 7 L - 5 R

**Comment by brylie** [comment]
I'll merge the changes so you can preview them in the sandbox environment.

**Comment by marycklein** [comment]
I like both these thischanges for desktop devices — column swap and resized image.

Do you think the image is unreasonably large for phone-sized screens to handle? If so, I am content to go with the next-smaller size.

??
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
The image size of 800 `px` max is relatively small, so should be fine for mobile devices. 

Here is a picture of the layout on a medium to large screen (I'm not sure exactly), taken from the sandbox site just now.

<img width="1294" alt="Screenshot 2023-01-24 at 19 01 04" src="https://user-images.githubusercontent.com/17307/214358513-b15e69e3-e777-4a6e-83c1-99df19dc6a97.png">

Here is a picture of the layout on an extra-large screen, taken from the sandbox site.

<img width="2501" alt="Screenshot 2023-01-24 at 18 58 16" src="https://user-images.githubusercontent.com/17307/214358050-0c0c81c8-36cd-4838-95d4-99317b2197d3.png">

**Comment by marycklein** [comment]
I think I like it. Thanks for the screenshot. I think it looks nice.

Will confess that I’m wavering a little over whether the image is actually “too big” now. But I think I should just try living with it for a few weeks and see how it settles in my mind.

THANKS for your good work!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
OK, cool. I'll close this issue as complete 😄
