### ISSUE TITLE
Footer - Social Media Links

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#785]
In website footer, 4 seems the right number of social media links to show; I think we should add Instagram and delete either Mastodon or Github. Our Mastodon presence is very weak. Brylie, do you think it would be helpful / useful to leave Github link? Content is probably less accessible for common WF reader, but maybe highly appreciated by those who would be interested.

**Comment by brylie** [comment]
I'd recommend removing the GitHub link since it isn't a conventional social media platform. We might also consider becoming more active on Mastadon network, such as by creating a profile on [Quakers.social](https://quakers.social/explore), featured in the following article: https://www.friendsjournal.org/quakers-turn-to-mastodon-social-media/

Perhaps we can add a small note at the very, very bottom of the page like, "We're open-source on GitHub"

**Comment by marycklein** [comment]
Four links to social platforms should display in our footer. In this order, they should be: FB, Instagram, Twitter (please keep original icon), and Mastodon.
Two still to be added are:
https://www.instagram.com/westernfriend/
https://mastodon.ie/@westernfriend
