### ISSUE TITLE
Note in "recent archive" re "deep archive"

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#788]
Maybe this could be accomplished by creating a dummy magazine issue, dated so that it displays where we want it, and with a "magazine cover" that conveys the note to reader.

![RevOne_2 3_note-re-deep-archive](https://github.com/WesternFriend/WF-website/assets/44241543/1f58e1f4-3f18-4e4d-8d6b-e8b42e7018ee)

**Comment by marycklein** [comment]
combine this with issue #857

**Comment by marycklein** [comment]
I shifted this to "minimum viable" because I think just a simple sentence below the sub-heading of "Recent Archive" would do. This would say:

For magazines older than 2013, see our “Deep Archive.” [This sentence could actually link to deep archive]

**Comment by brylie** [comment]
Since it was slightly easier to add the text in the intro text section, rather than code, I added the text with a link to the deep archive page after the intro text here:

https://staging.westernfriend.org/magazine/

![image](https://github.com/WesternFriend/WF-website/assets/17307/6890d1e9-c629-4917-9382-d2f65bf924e1)
