### ISSUE TITLE
Add protection for registration form (and possibly other forms)

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#817]
Implement a two-step registration process via django-registration.

If possible, add a solution for protecting public forms from SPAM submissions, such as the registration and contact forms.

Resources
- https://django-registration.readthedocs.io/en/3.0/activation-workflow.html
- https://learnwagtail.com/tutorials/adding-recaptcha-to-your-contact-forms/

**Comment by brylie** [comment]
I just took a look into this issue. There are a couple of primary options

- django-simple-captcha (https://djangopackages.org/packages/p/django-simple-captcha/)
- django-recaptcha (https://djangopackages.org/packages/p/django-recaptcha/)

The Django-recaptcha option looks good, and is maintained by Torchbox.

However, there isn't a clear path to get captcha support for Wagtail forms, as the main recaptcha module no longer seems to be maintained.

https://github.com/springload/wagtail-django-recaptcha

We could fork and update the package.

I'm moving this to post-launch to give more time for consideration.

**Comment by GT-Codeur** [comment]
Hello @brylie,
I wish to work on this. Please

**Comment by brylie** [comment]
Thank you @GT-Codeur. I'll assign you. Before coding any solution, let's use this issue to discuss the option(s) you see as the best way forward.

**Comment by brylie** [comment]
Let's use this approach for our contact form, @GT-Codeur 

https://learnwagtail.com/tutorials/adding-recaptcha-to-your-contact-forms/

**Comment by GT-Codeur** [comment]
Hello @brylie . Thanks for the orientation

**Comment by GT-Codeur** [comment]
Hello @brylie , sorry for delay. I was busy and since I'm newbie in wagtail, It took me time to understand how it function(and I'm still learning). From what I learnt, I have several questions:

1. Why the contact form is not complete on the UI? This is what I have :

![Screenshot from 2023-10-24 14-23-59](https://github.com/WesternFriend/WF-website/assets/19597695/df30d5d5-be4f-4847-a1f0-d70cd65283a7)

2. I think that this https://learnwagtail.com/tutorials/adding-recaptcha-to-your-contact-forms/ approach will work if we use registration form using wagtail form

**Comment by GT-Codeur** [comment]
I followed the tutorial, and I had this:
file:///home/germain/Pictures/Screenshots/Screenshot%20from%202023-10-28%2012-19-11.png

**Comment by brylie** [comment]
That looks good. Go ahead and open a pull request with your changes 😀
