### ISSUE TITLE
Subscribe / Donate - Disconnected from payment processor

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#889]
When "subscribing to magazine," after filling out name, etc., then clicking on "subscribe," the result is a page that says "Internal server error"

When attempting to "donate/pay," same thing happens.

**Comment by brylie** [comment]
Still getting authorization errors.

**Comment by brylie** [comment]
The authorization issue is related to the Braintree production system not letting us make actual transactions, to the best of my knowledge. From the best I can tell in the code, things should work correctly since I have tested the code with the Braintree sandbox. 

I opened a support request yesterday but have not yet heard back.

It may be good to think of a contingency plan, in case this is an issue with Braintree and we don't have any technical support.

**Comment by brylie** [comment]
On further review of the Braintree settings, there don't seem to be any allowed payment methods configured for our merchant account:

![image](https://github.com/WesternFriend/WF-website/assets/17307/399100b2-78e6-41cd-a2a3-8af00dcf2fe0)

This may be why we aren't "authorized" to make actual transactions.

**Comment by marycklein** [comment]
Let me know if there’s anything you need me to do at any time on this.
Or we can wait until our regular meeting in three days.
Or we can just plan to stick with PayPal for now, and revisit more expanded options later in the year ahead.

??
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
Discussed with @marycklein and decided to use PayPal
